name: MadFriends
version: 1.0.0
load: STARTUP
main: net.nektland.madfriends.MadFriends
description: An example plugin
author: PaperMC
website: https://papermc.io
api-version: '1.21.10'
depend: [UltimateAdvancementAPI]
softdepend: [UltimateAdvancementAPI]
commands:
  testCorpse:
    description: Main command for MadFriends plugin
    usage: /<command>
  testSpawnBlood:
    description: Main command for MadFriends plugin
    usage: /<command>
  TestMadmanSelect:
    description: Main command for MadFriends plugin
    usage: /<command>
